<?php

/**
 * @file
 * Contains installation and update routines for GovCore Page.
 */

/**
 * Implements hook_install().
 */
function govcore_landing_page_install() {
  $modules = [
    'govcore_workflow',
    'menu_ui',
    'metatag',
  ];

  $modules = array_filter($modules, [Drupal::moduleHandler(), 'moduleExists']);
  if ($modules) {
    govcore_landing_page_modules_installed($modules);
  }
}
