<?php

/**
 * @file
 * Contains installation and update routines for GovCore Roles.
 */

use Drupal\node\Entity\NodeType;

/**
 * Implements hook_install().
 */
function govcore_roles_install() {
  // Don't do anything during a config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  // Create content roles for all existing node types.
  $node_types = NodeType::loadMultiple();
  array_walk($node_types, 'govcore_roles_node_type_insert');
}
